"""Persistent code-workspace state.

This is deliberately text/state first: Swift owns editing UI; Python owns a
small JSON workspace per session so diagnostics, execution, and later local
LLM operations all operate on the same versioned source. Paths are logical
relative names only — the service never accepts an arbitrary filesystem path.
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path

from ..ipc.errors import ErrorCode, ProtocolError

_SAFE_FILE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{0,239}$")
_MAX_SOURCE_CHARACTERS = 500_000
# Bounds how much follow-up conversation context accumulates per file so a
# long-running session can't grow the workspace JSON unboundedly.
_MAX_HISTORY_ENTRIES = 10


@dataclass
class CodeFile:
    name: str
    language: str
    content: str
    version: int = 1
    # Bounded record of prior assist operations for this file — what makes
    # a follow-up request ("make this handle emoji") resolve against the
    # actual prior exchange instead of restarting from an empty prompt.
    # Metadata the *user* explicitly generated by asking for assistance on
    # their own workspace, not something read passively off a transcript —
    # distinct from the stderr/logging "never log source/prompt" rule.
    history: list[dict] = field(default_factory=list)


class CodeWorkspaceStore:
    def __init__(self, root: Path) -> None:
        self._root = root

    def get_file(self, session_id: str, name: str) -> CodeFile | None:
        return self._load(session_id).get(name)

    def list_files(self, session_id: str) -> list[CodeFile]:
        return list(self._load(session_id).values())

    def upsert_file(self, session_id: str, name: str, language: str, content: str, base_version: int | None) -> CodeFile:
        self._validate_name(name)
        self._validate_content(content)
        files = self._load(session_id)
        previous = files.get(name)
        if previous is not None and base_version is not None and previous.version != base_version:
            raise ProtocolError(ErrorCode.INVALID_PARAMS, "The code file changed; reload it before applying edits.")
        next_file = CodeFile(name=name, language=language or (previous.language if previous else "text"), content=content,
                             version=(previous.version + 1 if previous else 1),
                             history=list(previous.history) if previous else [])
        files[name] = next_file
        self._save(session_id, files)
        return next_file

    def apply_edits(self, session_id: str, name: str, base_version: int, edits: list[dict]) -> CodeFile:
        file = self.get_file(session_id, name)
        if file is None:
            raise ProtocolError(ErrorCode.SESSION_NOT_FOUND, "The requested code file does not exist.")
        if file.version != base_version:
            raise ProtocolError(ErrorCode.INVALID_PARAMS, "The code file changed; reload it before applying edits.")
        normalized: list[tuple[int, int, str]] = []
        for edit in edits:
            start, end, replacement = edit.get("start"), edit.get("end"), edit.get("replacement")
            if not isinstance(start, int) or not isinstance(end, int) or not isinstance(replacement, str):
                raise ProtocolError(ErrorCode.INVALID_PARAMS, "Each edit requires integer start/end and string replacement.")
            if start < 0 or end < start or end > len(file.content):
                raise ProtocolError(ErrorCode.INVALID_PARAMS, "A code edit range is outside the file.")
            normalized.append((start, end, replacement))
        # Reverse order makes every range refer to the original file and
        # rejects overlapping edits rather than silently corrupting code.
        normalized.sort(reverse=True)
        last_start = len(file.content) + 1
        content = file.content
        for start, end, replacement in normalized:
            if end > last_start:
                raise ProtocolError(ErrorCode.INVALID_PARAMS, "Code edits must not overlap.")
            content = content[:start] + replacement + content[end:]
            last_start = start
        return self.upsert_file(session_id, name, file.language, content, base_version)

    def append_history(self, session_id: str, name: str, operation: str, request: str, explanation: str) -> CodeFile:
        files = self._load(session_id)
        file = files.get(name)
        if file is None:
            raise ProtocolError(ErrorCode.SESSION_NOT_FOUND, "The requested code file does not exist.")
        entry = {"operation": operation, "request": request[:2000], "explanation": explanation[:2000]}
        file.history = (file.history + [entry])[-_MAX_HISTORY_ENTRIES:]
        files[name] = file
        self._save(session_id, files)
        return file

    def delete_session(self, session_id: str) -> None:
        path = self._path(session_id)
        try:
            path.unlink(missing_ok=True)
        except OSError as exc:
            raise ProtocolError(ErrorCode.INTERNAL_ERROR, "The local code workspace could not be deleted.") from exc

    def _path(self, session_id: str) -> Path:
        if not re.fullmatch(r"[A-Za-z0-9-]{1,64}", session_id):
            raise ProtocolError(ErrorCode.INVALID_PARAMS, "Invalid workspace session id.")
        return self._root / f"{session_id}.json"

    def _load(self, session_id: str) -> dict[str, CodeFile]:
        path = self._path(session_id)
        if not path.exists():
            return {}
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
            return {item["name"]: CodeFile(**item) for item in raw.get("files", [])}
        except (OSError, ValueError, TypeError, KeyError) as exc:
            raise ProtocolError(ErrorCode.INTERNAL_ERROR, "The local code workspace could not be read.") from exc

    def _save(self, session_id: str, files: dict[str, CodeFile]) -> None:
        path = self._path(session_id)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary = path.with_suffix(".tmp")
            temporary.write_text(json.dumps({"files": [asdict(file) for file in files.values()]}, separators=(",", ":")), encoding="utf-8")
            temporary.replace(path)
        except OSError as exc:
            raise ProtocolError(ErrorCode.INTERNAL_ERROR, "The local code workspace could not be saved.") from exc

    @staticmethod
    def _validate_name(name: str) -> None:
        if not isinstance(name, str) or not _SAFE_FILE_NAME.fullmatch(name) or ".." in name.split("/"):
            raise ProtocolError(ErrorCode.INVALID_PARAMS, "Code file names must be safe relative paths.")

    @staticmethod
    def _validate_content(content: str) -> None:
        if not isinstance(content, str) or len(content) > _MAX_SOURCE_CHARACTERS:
            raise ProtocolError(ErrorCode.INVALID_PARAMS, "Code file contents exceed the supported limit.")
